Repository Cloud-Drift/clouddrift, pull requests merged in 2023-11, with the labels that each got.

#307 `kinematics.spin` and `kinematics.eddy_kinetic_energy`
  clouddrift/kinematics.py
  pyproject.toml
  tests/kinematics_tests.py
Labels: enhancement, analysis-functions

#315 Add examples; fix formatting
  clouddrift/kinematics.py
  clouddrift/ragged.py
  clouddrift/signal.py
  clouddrift/sphere.py
  clouddrift/wavelet.py
Labels: documentation

#314 `rotary_transform` -> `cartesian_to_rotary`, `rotary_to_cartesian`
  clouddrift/signal.py
  tests/signal_tests.py
Labels: enhancement, analysis-functions

#316 Consistent lon, lat (instead of lat, lon) order for all functions
  clouddrift/kinematics.py
  clouddrift/sphere.py
  tests/sphere_tests.py
Labels: enhancement

#318 GLAD adapter and dataset accessor
  clouddrift/adapters/__init__.py
  clouddrift/adapters/glad.py
  clouddrift/datasets.py
  docs/api.rst
  docs/datasets.rst
  pyproject.toml
  tests/datasets_tests.py
Labels: enhancement, data-adapters

#324 Remove redundant coords assignment; test for dims and coords
  clouddrift/adapters/glad.py
  clouddrift/datasets.py
  tests/datasets_tests.py
Labels: bug

#258 start of plotting "help" module
  .github/workflows/ci.yml
  README.md
  clouddrift/__init__.py
  clouddrift/plotting.py
  docs/api.rst
  docs/install.rst
  tests/plotting_tests.py
Labels: enhancement
