Repository Cloud-Drift/clouddrift, pull requests merged in 2023-10, with the labels that each got.

#282 Gdp-update
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/datasets.py
Labels: data-adapters

#291 `analysis` -> `ragged` + `kinematics`
  clouddrift/__init__.py
  clouddrift/kinematics.py
  clouddrift/ragged.py
  clouddrift/raggedarray.py
  clouddrift/sphere.py
  docs/api.rst
  docs/usage.rst
  pyproject.toml
  tests/kinematics_tests.py
  tests/ragged_tests.py
Labels: enhancement

#292 Add a short contributing guide and scope
  README.md
Labels: documentation

#293 Write a CNAME file on every docs deploy
  .github/workflows/docs.yml
Labels: documentation

#303 redo of cumulative distance
  clouddrift/sphere.py
  tests/sphere_tests.py
Labels: enhancement, analysis-functions

#301 inertial extraction, take 2
  clouddrift/kinematics.py
  pyproject.toml
  tests/kinematics_tests.py
Labels: analysis-functions

#310 Inertial modifications
  clouddrift/kinematics.py
  tests/kinematics_tests.py
Labels: enhancement
