Repository Cloud-Drift/clouddrift, pull requests merged in 2023-09, with the labels that each got.

#248 More general subset
  clouddrift/analysis.py
Labels: enhancement

#247 Sphere-to-3d
  clouddrift/sphere.py
  tests/sphere_tests.py
Labels: enhancement, analysis-functions

#252 Allow time to be 1-d if u,v or lon,lat are n-d
  clouddrift/analysis.py
  tests/analysis_tests.py
Labels: enhancement, analysis-functions

#240 start of wavelet module
  clouddrift/__init__.py
  clouddrift/wavelet.py
  environment.yml
  pyproject.toml
  tests/wavelet_tests.py
Labels: enhancement, analysis-functions

#264 Allow subsetting by string or object ids
  clouddrift/analysis.py
  pyproject.toml
  tests/analysis_tests.py
Labels: bug

#257 Diagrams_in_doc
  clouddrift/analysis.py
  docs/api.rst
  docs/img/chunk.png
  docs/img/chunk_ragged.png
  docs/img/ragged_array.png
  docs/index.rst
Labels: documentation

#268 add wavelet module to doc?
  clouddrift/wavelet.py
  docs/api.rst
Labels: documentation

#259 wavelet transform fixes
  clouddrift/wavelet.py
  pyproject.toml
  tests/wavelet_tests.py
Labels: enhancement

#269 Cast GDP float64 data to float32 as an option (default)
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/raggedarray.py
Labels: data-adapters

#272 Add optional `rows` parameter to `unpack_ragged` and `apply_ragged`
  clouddrift/analysis.py
  tests/analysis_tests.py
Labels: enhancement

#278 subpages in the doc
  .gitignore
  clouddrift/wavelet.py
  docs/_templates/base.rst
  docs/_templates/class.rst
  docs/_templates/module.rst
  docs/api.rst
  docs/conf.py
Labels: documentation
