Repository Cloud-Drift/clouddrift, pull requests merged in 2023-03, with the labels that each got.

#111 Enable GDP experimental
  clouddrift/adapters/gdp.py
  clouddrift/dataformat.py
  tests/dataformat_tests.py
  tests/select_tests.py
Labels: enhancement, data-adapters

#145 Change example of apply_ragged
  clouddrift/analysis.py
Labels: documentation

#146 142-subset
  clouddrift/analysis.py
  clouddrift/select.py
  pyproject.toml
  tests/analysis_tests.py
  tests/select_tests.py
Labels: enhancement
