Repository Cloud-Drift/clouddrift, pull requests merged in 2023-08, with the labels that each got.

#219 signal module
  clouddrift/__init__.py
  clouddrift/signal.py
  docs/api.rst
  tests/signal_tests.py
Labels: enhancement, help wanted, analysis-functions

#220 MOSAiC dataset
  clouddrift/adapters/mosaic.py
  clouddrift/datasets.py
  docs/datasets.rst
  docs/index.rst
Labels: enhancement

#228 Nd-signal
  clouddrift/analysis.py
  clouddrift/signal.py
  tests/signal_tests.py
Labels: enhancement

#236 Update mosaic.py
  clouddrift/adapters/mosaic.py
Labels: enhancement

#239 Include start_* vars in GDP 6-hourly and hourly experimental
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/raggedarray.py
Labels: bug

#243 Fix N-d velocity and position functions with `time_axis`
  clouddrift/analysis.py
  pyproject.toml
  tests/analysis_tests.py
Labels: bug
