Repository Cloud-Drift/clouddrift, pull requests merged in 2023-12, with the labels that each got.

#330 Pairs module
  clouddrift/__init__.py
  clouddrift/pairs.py
  clouddrift/ragged.py
  docs/api.rst
  pyproject.toml
  tests/pairs_tests.py
  tests/ragged_tests.py
Labels: enhancement

#337 Update README.md
  README.md
Labels: documentation

#338 Subset by rows and pruning examples in docstring
  clouddrift/ragged.py
  tests/ragged_tests.py
Labels: documentation, enhancement

#334 Ellipse functions
  clouddrift/signal.py
  pyproject.toml
  tests/signal_tests.py
Labels: enhancement, analysis-functions

#322 yomaha and andro datasets
  clouddrift/adapters/__init__.py
  clouddrift/adapters/andro.py
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/adapters/subsurface_floats.py
  clouddrift/adapters/yomaha.py
  clouddrift/datasets.py
  docs/datasets.rst
  pyproject.toml
  tests/datasets_tests.py
Labels: data-adapters

#345 Refactor ellipse_parameters function in signal.py
  clouddrift/signal.py
Labels: bug

#336 Datasets consistency
  clouddrift/datasets.py
  clouddrift/ragged.py
  docs/datasets.rst
  pyproject.toml
  tests/datasets_tests.py
  tests/ragged_tests.py
Labels: bug
