Repository Cloud-Drift/clouddrift, pull requests merged in 2024-01, with the labels that each got.

#354 Update gdp datasets (fix)
  clouddrift/adapters/__init__.py
  clouddrift/adapters/andro.py
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/adapters/glad.py
  clouddrift/adapters/mosaic.py
  clouddrift/adapters/subsurface_floats.py
  clouddrift/adapters/utils.py
  clouddrift/adapters/yomaha.py
  clouddrift/datasets.py
  environment.yml
  pyproject.toml
  tests/datasets_tests.py
  tests/ragged_tests.py
Labels: bug

#362 Add new adapters to doc
  docs/api.rst
Labels: documentation, data-adapters

#364 subset docstring edit
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/adapters/glad.py
  clouddrift/adapters/mosaic.py
  clouddrift/datasets.py
  clouddrift/pairs.py
  clouddrift/ragged.py
  clouddrift/raggedarray.py
  clouddrift/wavelet.py
Labels: enhancement

#361 Subset callable using multiple variables
  clouddrift/ragged.py
  pyproject.toml
  tests/ragged_tests.py
Labels: enhancement, analysis-functions
