Repository Cloud-Drift/clouddrift, pull requests merged in 2024-02, with the labels that each got.

#365 ruff linting and formatting
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pypi.yml
  README.md
  clouddrift/__init__.py
  clouddrift/adapters/__init__.py
  clouddrift/adapters/andro.py
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/adapters/glad.py
  clouddrift/adapters/mosaic.py
  clouddrift/adapters/subsurface_floats.py
  clouddrift/adapters/utils.py
  clouddrift/adapters/yomaha.py
  clouddrift/datasets.py
  clouddrift/kinematics.py
  clouddrift/pairs.py
  clouddrift/plotting.py
  clouddrift/ragged.py
  clouddrift/raggedarray.py
  clouddrift/signal.py
  clouddrift/sphere.py
  clouddrift/wavelet.py
  pyproject.toml
  tests/datasets_tests.py
  tests/kinematics_tests.py
  tests/pairs_tests.py
  tests/plotting_tests.py
  tests/ragged_tests.py
  tests/raggedarray_tests.py
  tests/signal_tests.py
  tests/sphere_tests.py
  tests/wavelet_tests.py
Labels: enhancement

#371 Bug file downloading and typing
  .github/workflows/lint.yml
  .gitignore
  README.md
  clouddrift/_version.py
  clouddrift/adapters/andro.py
  clouddrift/adapters/gdp.py
  clouddrift/adapters/gdp1h.py
  clouddrift/adapters/gdp6h.py
  clouddrift/adapters/mosaic.py
  clouddrift/adapters/subsurface_floats.py
  clouddrift/adapters/utils.py
  clouddrift/adapters/yomaha.py
  clouddrift/datasets.py
  environment.yml
  pyproject.toml
  tests/__init__.py
  tests/adapters/gdp1h_integ_tests.py
  tests/adapters/gdp1h_tests.py
  tests/adapters/utils.py
  tests/adapters/utils_tests.py
Labels: data-adapters

#373 fix examples
  clouddrift/plotting.py
  tests/adapters/utils_tests.py
  tests/plotting_tests.py
Labels: documentation
