Repository Cloud-Drift/clouddrift, pull requests merged in 2024-08, with the labels that each got.

#502 ⭐️ new functions `index_to_row` and `rowsize_to_rowvector`
  clouddrift/ragged.py
  tests/ragged_tests.py
Labels: enhancement

#503 🧹 Update dataset URL to version 2.01.1
  clouddrift/datasets.py
Labels: bug

#413 ⭐ raw, position and sensor data gdp drifter dataset adapter
  clouddrift/adapters/__init__.py
  clouddrift/adapters/gdp/__init__.py
  clouddrift/adapters/gdp/gdp1h.py
  clouddrift/adapters/gdp/gdp6h.py
  clouddrift/adapters/gdp/gdpsource.py
  clouddrift/datasets.py
  docs/datasets.rst
  tests/adapters/gdp/__init__.py
  tests/adapters/gdp/gdp1h_integ_tests.py
  tests/adapters/gdp/gdp1h_tests.py
  tests/adapters/gdp/gdp6h_integ_tests.py
  tests/adapters/gdp/gdp6h_tests.py
  tests/adapters/gdp/source_integ_tests.py
Labels: enhancement

#513 🔍 Add email distribution list registration form
  README.md
Labels: documentation
