Repository Cloud-Drift/clouddrift, pull requests merged in 2024-04, with the labels that each got.

#387 🐛 use zarr archive for gdp6h dataset
  clouddrift/datasets.py
Labels: enhancement

#388 🔧 update retry config and keep completed downloads
  clouddrift/adapters/utils.py
  tests/adapters/utils_tests.py
Labels: data-adapters

#389 🐛 fix mosaic dataset bug, using empty buffers
  clouddrift/adapters/mosaic.py
  clouddrift/adapters/utils.py
  tests/datasets_tests.py
Labels: data-adapters

#381 🔧 Integrate doctest to run on our `ragged.py` module
  .github/workflows/ci.yml
  clouddrift/adapters/gdp1h.py
  clouddrift/ragged.py
  tests/docexamples.py
Labels: enhancement

#409 🔍 Documentation update
  .vscode/tasks.json
  clouddrift/adapters/hurdat2.py
  clouddrift/datasets.py
  docs/api.rst
  docs/conf.py
  docs/datasets.rst
  docs/index.rst
Labels: documentation
